services:
  quotes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quotes
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
